### PR TITLE
Update firewall module dependency

### LINKED ISSUE #2: 'martezr-rdp' (v0.1.2) requires 'rmsphd-windows_firewall' (>= 0.1.0 <5.0.0)
Warning: Module 'rmsphd-windows_firewall' (v0.0.3) fails to meet some dependencies:
  'martezr-rdp' (v0.1.2) requires 'rmsphd-windows_firewall' (>= 0.1.0 <5.0.0)

Please correct pined versions for rmsphd-windows_firewall.

### PR DESCRIPTION
**Pull request by jordigg**
Resolves #2 
Update firewall module dependency from rmsphd-windows_firewall (unmaintained) to updated/maintained fork puppet-windows_firewall https://forge.puppet.com/puppet/windows_firewall

### CODE REVIEW

**Comment by martezr** [comment]
Thanks for updating the module.

**Comment by jordigg** [comment]
Is it possible to merge the PR and release a new version on forge? Are you still maintaining it?

**Comment by martezr** [comment]
Working on getting the PR merged now

**Comment by jordigg** [comment]
do you see the `Checking for ability to merge automatically…` message? Have the same on my fork, maybe something went wrong while forking the project. Should I do it again? Feel free to change the code on your project and cancel this PR if makes things easier.

**Comment by martezr** [comment]
The PR still isn't showing up correctly so I updated the modulefile and metadata.json file separately.

**Pull request closed without merging**
